import type { Metadata } from "next";
import { RatioSetter } from "@common";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RatioSetter>{children}</RatioSetter>
      </body>
    </html>
  );
}
